config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  get 'dashboard', to: 'dashboards#dashboard', as: 'dashboard'

  patch 'status/:id', to: 'bookings#status', as: 'status'

  resources :coaching_offers, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, except: :show
  end

  resources :bookings, only: [:show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  # resources :dashboard, only: [:show] do
  #   resources :bookings, only: [:edit, :update, :destroy]
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :coaching_offer
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :datetime, presence: true
  # validates :datetime TO BE only possible for "tomorrow"
  validates :duration, presence: true
  validates :status, inclusion: { in: ["pending", "accepted", "rejected"] }

end

app/models/coaching_offer.rb
class CoachingOffer < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_description_skill,
  against: [ :title, :description, :skill ],
  using: {
    tsearch: { prefix: true }
  }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :title, length: { minimum: 5, maximum: 30 }
  validates :description, length: { minimum: 20, maximum: 400 }
  validates :price, presence: true
  validates :user, presence: true
  validates :skill, inclusion: { in: ["Ruby", "Rails", "JavaScript", "HTML", "CSS", "FrontEnd", "BackEnd", "Python", "PHP"] }

  def average_rating
    reviews.average(:rating) || 0
  end

  # def offer_reviews
  #    bookings.extract_associated(:reviews)
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :rating, presence: true
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :coaching_offers
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_pic, presence: true

  has_one_attached :profile_pic

  # validates_attachment :profile_pic, :content_type => { :content_type => /\Aimage\/jpg/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_pic])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :profile_description, :skills, :profile_pic])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy, :status]

  #read

  def index
    @bookings = Bookings.all
  end

  def show
  end

  #create
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @coaching_offer = CoachingOffer.find(params[:coaching_offer_id])
    @booking.coaching_offer = @coaching_offer
    if @booking.save
      redirect_to booking_path(@booking), notice: "Yeaaaayyyyyy"
    else
      render "coaching_offers/show", status: :unprocessable_entity
    end
  end

  #update
  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to dashboard_path(@booking)
  end

  #delete
  def destroy
    @booking.destroy
    redirect_to dashboard_url, notice: "The booking was deleted."
  end

  def status
    @booking.status = params[:status]
    @booking.save
    redirect_to dashboard_path
  end


  private

  def booking_params
    params.require(:booking).permit(:datetime, :duration, :comment)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/coaching_offers_controller.rb
class CoachingOffersController < ApplicationController

  before_action :set_coaching_offer, only: [:show, :edit, :update, :destroy, :status]

  def index
    query = params[:query]
    if query.present?
      @coaching_offers = CoachingOffer.search_by_title_description_skill(query)
    else
      @coaching_offers = CoachingOffer.all
    end
  end

  def show
    @coaching_offer = CoachingOffer.find(params[:id])
    @coaching_offers = CoachingOffer.where(user: @coaching_offer.user).excluding(@coaching_offer)
    @booking = Booking.new
    @offer_reviews = @coaching_offer.reviews
  end

  def new
    @coaching_offer = CoachingOffer.new
  end

  def create
    @coaching_offer = CoachingOffer.new(coaching_offer_params)
    @coaching_offer.user = current_user
    if @coaching_offer.save
      redirect_to coaching_offer_path(@coaching_offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # ****
  #update
  def edit
  end

  def update
    @coaching_offer.update(coaching_offer_params)
    redirect_to dashboard_path(@coaching_offer)
  end

  #delete
  def destroy
    @coaching_offer.destroy
    redirect_to dashboard_url, notice: "The offer was deleted."
  end

  def status
    @coaching_offer.status = params[:status]
    @coaching_offer.save
    redirect_to dashboard_path
  end


  private

  def coaching_offer_params
    params.require(:coaching_offer).permit(:skill, :description, :price, :title, :rating)
  end

  def set_coaching_offer
    @coaching_offer = CoachingOffer.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @coachee_bookings = current_user.bookings
    @coach_bookings = current_user.coaching_offers.extract_associated(:bookings).flatten
    @your_offers = current_user.coaching_offers
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @bookings = Booking.all
    # TODO: make another selection of offers to show on homepage
    @coaching_offers = CoachingOffer.where(rating: (4..5))
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @coaching_offer = @booking.coaching_offer
    @review = Review.new
    # render "reviews/new", status: :unprcessable_entity
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      flash[:notice] = "Review created successfully"
      redirect_to booking_path(@booking)
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="grid-edit-booking">
  <div class="edit-booking-form container">
    <div class="edit-booking-form-heading container">
      Edit your booking:
    </div>
    <%= simple_form_for @booking do |f| %>
      <div>
        <%= f.input :datetime, as: :datetime, html5: true, label: "Pick up a date and time", input_html:{ class: "edit-booking-form-inputs"}%>
        <%= f.input :duration, label: "How many hours do you need?", input_html:{ class: "edit-booking-form-inputs"}%>
      </div>

      <div>
        <%= f.input :comment, input_html:{ class: "edit-booking-comment-input"} %>
      </div>

      <div class="booking-form-actions">
        <%= f.submit "save changes", class: "btn-salmon" %>
      </div>
    <% end %>
  </div>

  <div class="confirmation-img">
    <%= image_tag "illustrations/undraw_content_team_re_6rlg.svg", alt: "text", class: "image-edit-booking"%>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container container-conf">
  <div class="confirmation-info">
    <div class="confirmation-text">
      <h1>Help is on the way! 🎉🎉</h1>
      <p>We have received your booking request and will let you know once the coach has accepted.</p>
    </div>

    <div class="confirm-buttons">
      <%= link_to "View your bookings", dashboard_path, class: "btn btn-ghost btn-salmon" %>
      <br>
      <%= link_to "Back to the offer", coaching_offer_path, class: "btn btn-ghost" %>
    </div>
  </div>

  <div class="confirmation-img">
    <%= image_tag "illustrations/undraw_team_up_re_84ok.svg", alt: "text", class: "image-confirmation"%>
  </div>
</div>

app/views/coaching_offers/edit.html.erb
<div class="container">
  <h2 class="my-5">Edit your offer</h2>

  <div class="create_offer_form">
    <%= simple_form_for @coaching_offer do |f| %>
      <%= f.input :skill, collection: ["Ruby", "Rails", "JavaScript", "HTML", "CSS", "FrontEnd", "BackEnd", "Python", "PHP"] %>
      <%= f.input :title %>
      <%= f.input :description, as: :text %>
      <%= f.input :price %>
      <%= f.submit 'Save offer', class: "a-btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/coaching_offers/index.html.erb
<div class="container">
  <div class="my-5">
    <h2> Current offers from our coaches:</h2>
  </div>

  <div class="grid">
    <% @coaching_offers.each do |offer| %>
      <%= render "shared/offer_card", offer: offer %>
    <% end %>
  </div>
</div>
<%#why is this not working???  %>

app/views/coaching_offers/new.html.erb
<div class="container">
  <h2 class="my-5">Create your offer</h2>

  <div class="create_offer_form">
    <%= simple_form_for @coaching_offer do |f| %>
      <%= f.input :skill, collection: ["Ruby", "Rails", "JavaScript", "HTML", "CSS", "FrontEnd", "BackEnd", "Python", "PHP"] %>
      <%= f.input :title %>
      <%= f.input :description, as: :text %>
      <%= f.input :price %>
      <%# MAYBE ..maybe ..change input for :price to range with some JS showing the selected value %>
        <%#= f.input :data, as: :range, input_html:{ min:"0", max:"45", oninput:"updateTextInput(this.value)"}%>
        <%# <script>
        function updateTextInput(val) {
                  document.getElementById('textInput').value=val;
                }
        </script> %>
      <%= f.submit 'Save offer', class: "a-btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/coaching_offers/show.html.erb
<div class="container">
  <h2 class="my-5">Your chosen <strong>coaching</strong></h2>
  <div class="show-content">

    <div class="offer_card">
      <div class="img_info my-3">
        <div class="skill-image">
          <%= image_tag "skills/#{@coaching_offer.skill}.png", alt: "#{@coaching_offer.skill} Logo" %>
        </div>
        <div class="profile-image">
          <%= cl_image_tag @coaching_offer.user.profile_pic.key %>
        </div>
        <div class="infos">
          <div class="full-name">
            <%= @coaching_offer.user.first_name %>
            <%= @coaching_offer.user.last_name %>
          </div>
          <div class="skills">
            Skill:
            <%= @coaching_offer.skill %>
          </div>
          <div class="rating_price">
            <div class="rating">
              <% if @coaching_offer.rating %>
                <% @coaching_offer.rating.floor.times do %>
                  <%= image_tag "star.png", alt: "alttext", class: "star-rating" %>
                <% end %>
              <% else %>
                <small>No ratings yet.</small>
              <% end %>
            </div>
            <div class="price-offer">
              $<%= @coaching_offer.price %>/h
            </div>
          </div>
        </div>
      </div>
      <div class="offer_description">
        <%= @coaching_offer.title %>
        <br>
        <%= @coaching_offer.description %>
      </div>
    </div>

    <div class="booking-form">
      <div class="booking-form-heading">
        Book coaching now!
      </div>
      <%= simple_form_for [@coaching_offer, @booking] do |f| %>
        <div>
          <%= f.input :datetime, as: :datetime, html5: true, label: "Pick up a date and time", input_html:{ class: "booking-form-inputs"}%>
          <%= f.input :duration, label: "How many hours do you need?", input_html:{ class: "booking-form-inputs"}%>
        </div>

        <div>
          <%= f.input :comment, input_html:{ class: "booking-comment-input"} %>
        </div>

        <div class="booking-form-actions">
          <%= f.submit "Book coaching", class: "btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="my-5">
    <h2> Other offers from <strong><%= @coaching_offer.user.first_name %> <%= @coaching_offer.user.last_name %></strong>:</h2>
  </div>

  <div class="grid">
    <% @coaching_offers.each do |offer| %>
      <%= render "shared/offer_card", offer: offer %>
    <% end %>
  </div>

  <% unless @coaching_offer.reviews.blank? %>
    <div class="container show-content my-5">
      <h2>Reviews of this course</h2>
    </div>
    <div class="reviews-wrapper">
      <div class="review-cards">
        <% @offer_reviews.each do |review|%>
          <div class="card-review">
            <%= image_tag review.booking.user.profile_pic, alt: "alttext" %>
            <div class="card-review-infos">
              <div>
                <h2><%= review.title %></h2>
                <p><%= review.description %></p>
                <small> <%= review.booking.user.first_name %></small>
              </div>
              <div class="ratings">
                <% review.rating.times do %>
                  <%= image_tag "star.png", alt: "alttext", class: "star-rating" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboards/dashboard.html.erb
<div class="container mt-5">
  <h2>Your Dashboard, <%= current_user.first_name %></h2>
  <nav class="mt-5">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">See as a Coachee</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">See as a Coach</button>
      <button class="nav-link" id="nav-offers-tab" data-bs-toggle="tab" data-bs-target="#nav-offers" type="button" role="tab" aria-controls="nav-offers" aria-selected="false">Your offers</button>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <% if @coachee_bookings.empty? == false %>
        <div class="pending-req-student-perspective">
          <h3 class="mt-5">You have booked the following coaching sessions:</h3>
          <div class="mt-5">
            <% if @coachee_bookings == [] %>
              <p>You haven't booked a coach, yet.</p>
              <%= link_to "Book a coach", coaching_offers_path, class: "btn-flat a-btn ms-2" %>
            <% else %>
              <% @coachee_bookings.each do | booking | %>
                <div class="card-product">
                  <%= image_tag "skills/#{booking.coaching_offer.skill}.png", alt: "#{booking.coaching_offer.skill} Logo" %>
                  <div class="card-product-infos flex-grow-1">
                    <p><strong>Date: <%= booking.datetime.strftime("%d %b %Y, %H:%M") %></strong></p>
                    <p><strong>Offer: </strong><%= booking.coaching_offer.title %></p>
                    <p><strong>Coaching hours: </strong><%= booking.duration %> h</p>
                    <p><strong>Coach name: </strong><%= booking.coaching_offer.user.first_name %> <%=booking.coaching_offer.user.last_name%></p>
                    <p><strong>Skill: </strong><%= booking.coaching_offer.skill %></p>
                    <p><strong>Comment: </strong><%= booking.comment %></p>
                    <div class="flex-grow-1 text-end">
                      <%= link_to "Contact the coach", "#{booking.coaching_offer.user.email}", class: "btn-ghost a-btn ms-2" %>
                      <%= link_to "Edit Request", edit_booking_path(booking), class: "btn-ghost a-btn ms-2" %>
                      <%= link_to "Delete Request", booking_path(booking), data: { turbo_method: :delete}, class: "btn-ghost a-btn ms-2" %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% else %>
      <h3 class="mt-5 mb-5 text-center">You haven't booked a coach!</h3>
        <span class="d-grid gap-2 col-3 mx-auto"><%= link_to "Book a coach", coaching_offers_path, class: "btn-flat a-btn ms-2 text-center" %></span>
      <% end %>
    </div>





    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
      <% if @coach_bookings.empty? == false %>
        <div class="pending-req-coach-perspective">
          <h3 class="mt-5">Accept your pending requests and start helping others:</h3>
          <div class="mt-5">
            <% if @coach_bookings.empty? %>
              <p>You have no pending requests to accept!</p>
            <% else %>
              <% @coach_bookings.each do | booking | %>
                <div class="card-product">
                  <%= image_tag "skills/#{booking.coaching_offer.skill}.png", alt: "#{booking.coaching_offer.skill} Logo" %>
                  <div class="card-product-infos flex-grow-1">
                    <h2>Date: <%= booking.datetime.strftime("%d %b %Y, %H:%M") %></h2>
                    <p><strong>Coaching hours: </strong><%= booking.duration %> h</p>
                    <p><strong>Potential Earnings:</strong>  US$ <%= booking.duration * booking.coaching_offer.price %>.00</p>
                    <p><strong>Request from: </strong><%= booking.user.first_name %> <%=booking.user.last_name%></p>
                    <p><strong>Offer Ref: </strong><%= booking.coaching_offer.title %></p>
                    <p><strong>Skill: </strong><%= booking.coaching_offer.skill %></p>
                    <%= link_to "Contact the coachee", "#{booking.user.email}", class: "btn-ghost a-btn ms-2" %>
                    <div class="flex-grow-1 text-end">
                       <% if booking.status == "accepted" %>
                        <h5 class=booking-status>🎉 Booking Confirmed</h5>
                        <%= link_to "Reject Request", status_path(booking.id, status: "rejected"), data: {turbo_method: :patch}, class: "btn-ghost a-btn ms-2" %>
                      <% elsif booking.status == "rejected" %>
                        <h5 class=booking-status>😢 Booking Rejected</h5>
                        <%= link_to "Accept Request", status_path(booking.id, status: "accepted"), data: {turbo_method: :patch}, class: "btn-flat a-btn ms-2" %>
                        <%= link_to "Delete Request", booking_path(booking), data: { turbo_method: :delete}, class: "btn-ghost a-btn ms-2" %>
                      <% else %>
                        <%= link_to "Reject Request", status_path(booking.id, status: "rejected"), data: {turbo_method: :patch}, class: "btn-ghost a-btn ms-2" %>
                        <%= link_to "Accept Request", status_path(booking.id, status: "accepted"), data: {turbo_method: :patch}, class: "btn-flat a-btn ms-2" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      <% else %>
      <h3 class="mt-5 mb-5 text-center">You have no coaching requests!</h3>
      <span class="d-grid gap-2 col-3 mx-auto"><%= link_to "Create a Coaching Offer", new_coaching_offer_path, class: "btn-flat a-btn ms-2 text-center" %></span>
      <% end %>
    </div>

    <div class="tab-pane fade" id="nav-offers" role="tabpanel" aria-labelledby="nav-offers-tab" tabindex="0">
      <% if @your_offers.empty? == false %>
        <div class="your-offers-list">
          <h3 class="mt-5">Your coaching offers:</h3>
          <div class="mt-5">
            <% if @your_offers.empty? %>
              <p>You haven't posted any coaching offers yet</p>
            <% else %>
              <div class="your-offers">
                <% @your_offers.each do | offer | %>
                    <div class="your-offer-card">
                      <div class="your-offer-card-head">
                        <div class="skill-image">
                          <%= image_tag "skills/#{offer.skill}.png", alt: "#{offer.skill} Logo" %>
                        </div>
                        <div class="infos">
                          <div class="skills">
                            Skill:
                            <%= offer.skill %>
                          </div>
                          <div class="rating_price">
                            <div class="rating">
                              <% if offer.rating %>
                                <% offer.rating.floor.times do %>
                                  <%= image_tag "star.png", alt: "alttext", class: "star-rating" %>
                                <% end %>
                              <% else %>
                                <small>No ratings yet.</small>
                              <% end %>
                            </div>
                            <div class="price-offer">
                              Price: $<%= offer.price %>/h
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="offer_description">
                        <%= offer.title %>
                        <br>
                        <%= offer.description %>
                      </div>
                      <div class="flex-grow-1 text-end your-offer-buttons">
                        <%= link_to "Edit", edit_coaching_offer_path(offer), class: "btn-ghost a-btn ms-2" %>
                        <%= link_to "Delete", coaching_offer_path(offer), data: { turbo_method: :delete}, class: "btn-ghost a-btn ms-2" %>
                      </div>
                    </div>
                  <% end %>
                </div>
            <% end %>
            </div>
          </div>
        </div>
      <% else %>
      <h3 class="mt-5 mb-5 text-center">You have no coaching requests!</h3>
      <span class="d-grid gap-2 col-3 mx-auto"><%= link_to "Create a Coaching Offer", new_coaching_offer_path, class: "btn-flat a-btn ms-2 text-center" %></span>
      <% end %>
    </div>



  </div>
  <%# <% if @coachee_bookings.empty? && @coach_bookings.empty? %>
    <%# <h2>You have no bookings!</h2> %>
    <%# add buttons: create a coaching offer or book a coach %>
  <%# end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirCoaches</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="icon" a href="https://cdn-icons-png.flaticon.com/512/759/759823.png" type="image/x-icon">
  </head>


  <body>
    <div class="content">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>


    <div class="footer">
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1528901166007-3784c7dd3653?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80);">
  <div class="container">
    <h1><span data-controller="typed-js"></span></h1>
    <p>Get help, learn faster and finish your projects today!</p>
    <% if user_signed_in? %>
      <%= link_to "Get started", dashboard_path, class: "btn btn-flat" %>
    <% else %>
      <%= link_to "Get started", new_user_registration_path, class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="my-5">
    <h2> Top rated offers from our coaches:</h2>
  </div>

  <div class="grid">
    <% @coaching_offers.each do |offer| %>
      <%= render "shared/offer_card", offer: offer %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class="my-5 ms-5">Create a new review for <%= @coaching_offer.title %> </h1>
    <div class="create_offer_form">
    <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :rating %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="sticky-top navbar navbar-expand-sm navbar-light navbar-ac border-bottom border-1">
  <div class="container container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <div class="d-flex align-items-center">
          <li class="nav-item ms-3">
            <%= form_with url: coaching_offers_path, method: :get, class: "search-navbar d-flex" do %>
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a coaching..." %>
                <%= button_tag(class: "btn btn-ghost") do %>
                  <i class="fa-solid fa-magnifying-glass"></i>
                <% end %>
            <% end %>
          </li>
          <li class="nav-item ms-3">
            <%= link_to "Book a coach!", coaching_offers_path, class: "btn btn-flat" %>
          </li>
        </div>
        <% if user_signed_in? %>
          <li class="nav-item ms-3 dropdown">
            <% if current_user.profile_pic.attached? %>
              <%= cl_image_tag current_user.profile_pic.key, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "undraw_Female_avatar_re_l6cx.png", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Show Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Create a coaching offer", new_coaching_offer_path, class: "dropdown-item" %>
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
         <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-ghost btn-login" %>
        <% end %>
      </ul>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>